### PR TITLE
add Chinese translation

### PR DESCRIPTION
**Pull request by moonlooker**
Chinese Translation of Additional Settings Interface

### CODE REVIEW

**Comment by s3-chardonjf** [comment]
Hello @moonlooker , thank you for your interest and contribution! However we'd like more information regarding the new dash.exe you want to submit. What's that one about? Thank you!

**Comment by moonlooker** [comment]
> Hello @moonlooker , thank you for your interest and contribution! However we'd like more information regarding the new dash.exe you want to submit. What's that one about? Thank you!

i donot modify dash.exe. just only translate language.

all commit about CN content.

**Comment by s3-chardonjf** [comment]
https://github.com/sector3studios/webhud/pull/2/files begs to differ?

**Comment by moonlooker** [comment]
> https://github.com/sector3studios/webhud/pull/2/files begs to differ?

Sorry,  this is my test compiler . Should the content of dist not be uploaded?

**Comment by s3-chardonjf** [comment]
There shouldn't be any need for .exe and .dll's just to add a new language.

**Comment by moonlooker** [comment]
> here shouldn't be any need for .exe and .dll's just to add a new language.

> here shouldn't be any need for .exe and .dll's just to add a new language.

ok, i will fix it.

**Pull request closed without merging**
